# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.cache/wt} [current_project]
set_property parent.project_path {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/SA_EXTEND.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/TWO_TO_ONE.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/THREE_TO_ONE.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/REGISTER_FILE.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/PC_OFFSET.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/PC_JUMP.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/PC_ADD_FOUR.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/PC.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/NUMBER_EXTEND.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/NEXT_STATE.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/IR.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/INS_MEM_RW.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/INS_DEC.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/FOUR_TO_ONE.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/D_FLIP_FLOP.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/DR.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/DATA_MEM.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/CONTROL_UNIT.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/ALU.v}
  {E:/Computer Organization/Experiment/MultiCycleCpu/MultiCycleCpu/MultiCycleCpu.srcs/sources_1/new/MULTI_CUCLE_CPU.v}
}
synth_design -top MULTI_CUCLE_CPU -part xc7a35tcpg236-1
write_checkpoint -noxdef MULTI_CUCLE_CPU.dcp
catch { report_utilization -file MULTI_CUCLE_CPU_utilization_synth.rpt -pb MULTI_CUCLE_CPU_utilization_synth.pb }
