# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.cache/wt} [current_project]
set_property parent.project_path {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/sources_1/imports/SingleCycleCpu.srcs/sources_1/new/SignZeroExtend.v}
  {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/sources_1/new/SegLED.v}
  {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/sources_1/imports/SingleCycleCpu.srcs/sources_1/new/RegSelect.v}
  {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/sources_1/imports/SingleCycleCpu.srcs/sources_1/new/RegisterFile.v}
  {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/sources_1/imports/SingleCycleCpu.srcs/sources_1/new/PCSelect.v}
  {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/sources_1/imports/SingleCycleCpu.srcs/sources_1/new/PCI.v}
  {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/sources_1/imports/SingleCycleCpu.srcs/sources_1/new/PC4.v}
  {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/sources_1/imports/SingleCycleCpu.srcs/sources_1/new/PC.v}
  {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/sources_1/imports/SingleCycleCpu.srcs/sources_1/new/JumpOp.v}
  {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/sources_1/imports/SingleCycleCpu.srcs/sources_1/new/InstructionMemory.v}
  {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/sources_1/imports/SingleCycleCpu.srcs/sources_1/new/InsMemRW.v}
  {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/sources_1/imports/SingleCycleCpu.srcs/sources_1/new/DataSelect.v}
  {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/sources_1/imports/SingleCycleCpu.srcs/sources_1/new/DataMemory.v}
  {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/sources_1/imports/SingleCycleCpu.srcs/sources_1/new/ControlUnit.v}
  {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/sources_1/imports/SingleCycleCpu.srcs/sources_1/new/ALUSrcSelect.v}
  {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/sources_1/imports/SingleCycleCpu.srcs/sources_1/new/ALU.v}
  {E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/sources_1/imports/SingleCycleCpu.srcs/sources_1/new/SingleStyleCPU.v}
}
read_xdc {{E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/constrs_1/new/ports.xdc}}
set_property used_in_implementation false [get_files {{E:/Computer Organization/Experiment/SingleCycleCpu/SingleCycleCpu_Basys3/SingleCycleCpu_Basys3.srcs/constrs_1/new/ports.xdc}}]

synth_design -top SingleStyleCPU -part xc7a35tcpg236-1
write_checkpoint -noxdef SingleStyleCPU.dcp
catch { report_utilization -file SingleStyleCPU_utilization_synth.rpt -pb SingleStyleCPU_utilization_synth.pb }
